const { createClient } = require('@supabase/supabase-js')
const { put, del } = require('@vercel/blob')

const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

function client(req) {
  const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, '')
  return createClient(supabaseUrl, supabaseKey, { global: { headers: token ? { Authorization: `Bearer ${token}` } : {} } })
}
async function userFor(req) {
  const { data, error } = await client(req).auth.getUser()
  if (error || !data.user) throw new Error('UNAUTHORIZED')
  return data.user
}
function json(res, status, body) { res.status(status).json({ status_code: status, ...body }) }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => raw += c); req.on('end', () => { try { const contentType = String(req.headers['content-type'] || '').toLowerCase(); if (contentType.includes('application/x-www-form-urlencoded')) return resolve(Object.fromEntries(new URLSearchParams(raw))); resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('INVALID_JSON')) } }) }) }
function path(req) { return new URL(req.url, `https://${req.headers.host || 'localhost'}`).pathname.replace(/^\/api\/?/, '') }
function profileShape(row) { return { ...row, birthday: row.birthday || row.birth_date || null, birth_date: row.birth_date || row.birthday || null, profile_picture: row.profile_picture || null, first_name: row.first_name || 'Liebena member', flight_mode: Boolean(row.flight_mode) } }

async function register(req, res) {
  const input = await body(req)
  const email = String(input.email || '').trim().toLowerCase(); const password = String(input.password || '')
  if (!email || password.length < 6) return json(res, 400, { message: 'Email and password are required.' })
  const { data, error } = await client(req).auth.signUp({ email, password, options: { data: { first_name: input.first_name || null, last_name: input.last_name || null } } })
  if (error) return json(res, 400, { message: error.message })
  if (data.session?.access_token && data.user) {
    const authenticatedClient = createClient(supabaseUrl, supabaseKey, { global: { headers: { Authorization: `Bearer ${data.session.access_token}` } } })
    const { error: profileError } = await authenticatedClient.from('liebena_profiles').upsert({ id: data.user.id, email, first_name: input.first_name || null, last_name: input.last_name || null, passion: input.passion || null, birth_date: input.birthday || input.birth_date || null, gender: input.gender || null, interested_in: input.interests || null, display_gender: Boolean(Number(input.display_gender)), latitude: Number.isFinite(Number(input.latitude)) ? Number(input.latitude) : null, longitude: Number.isFinite(Number(input.longitude)) ? Number(input.longitude) : null, location_updated_at: new Date().toISOString(), flight_mode: Boolean(input.flight_mode) }).select().single()
    if (profileError) return json(res, 400, { message: profileError.message })
  }
  return json(res, 201, { token: { access_token: data.session?.access_token || '' }, user: data.user })
}
async function login(req, res) {
  const input = await body(req); const { data, error } = await client(req).auth.signInWithPassword({ email: input.username || input.email, password: input.password })
  if (error || !data.session) return json(res, 401, { message: 'Invalid email or password.' })
  json(res, 200, { access_token: data.session.access_token, refresh_token: data.session.refresh_token, token_type: 'bearer' })
}
async function profile(req, res) {
  const user = await userFor(req); const supabase = client(req)
  if (req.method === 'GET') { const { data, error } = await supabase.from('liebena_profiles').select('*').eq('id', user.id).single(); if (error) return json(res, 404, { message: 'Profile not found.' }); return json(res, 200, { user: profileShape(data) }) }
  const input = await body(req); const { data, error } = await supabase.from('liebena_profiles').upsert({ id: user.id, email: user.email, first_name: input.first_name, last_name: input.last_name, passion: input.passion, phone_number: input.phone_number, birth_date: input.birth_date || input.birthday, gender: input.gender, interested_in: input.interests, display_gender: Boolean(Number(input.display_gender)), bio: input.bio, flight_mode: Boolean(input.flight_mode), updated_at: new Date().toISOString() }).select().single(); if (error) return json(res, 400, { message: error.message }); return json(res, 200, { user: profileShape(data), message: 'Profile updated.' })
}
function distanceKm(lat1, lon1, lat2, lon2) { const earth = 6371; const rad = (value) => value * Math.PI / 180; const dLat = rad(lat2 - lat1); const dLon = rad(lon2 - lon1); const a = Math.sin(dLat / 2) ** 2 + Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(dLon / 2) ** 2; return earth * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
async function users(req, res) { const user = await userFor(req); const supabase = client(req); const params = new URL(req.url, 'https://localhost').searchParams; const minAge = Number(params.get('min_age') || 18); const maxAge = Number(params.get('max_age') || 80); const maxDistance = Number(params.get('distance') || 50); const interestedGender = params.get('gender'); const { data: me, error: meError } = await supabase.from('liebena_profiles').select('latitude,longitude,interested_in,birth_date,flight_mode').eq('id', user.id).single(); if (meError || me?.latitude == null || me?.longitude == null) return json(res, 412, { message: 'Location is required before discovering matches.' }); const { data: swipes } = await supabase.from('liebena_swipes').select('target_id').eq('swiper_id', user.id); const excluded = new Set((swipes || []).map(row => row.target_id)); const { data, error } = await supabase.from('liebena_profiles').select('*').neq('id', user.id).not('latitude', 'is', null).not('longitude', 'is', null).order('created_at', { ascending: false }); if (error) return json(res, 400, { message: error.message }); const now = new Date(); const result = (data || []).filter(profile => { if (excluded.has(profile.id)) return false; if (interestedGender && interestedGender !== 'any' && profile.gender !== interestedGender) return false; if (me.interested_in && me.interested_in !== 'any' && profile.gender !== me.interested_in) return false; if (profile.interested_in && profile.interested_in !== 'any' && profile.interested_in !== me.gender) return false; const birthday = profile.birth_date || profile.birthday; const age = birthday ? Math.floor((now - new Date(birthday)) / 31557600000) : 0; if (age < minAge || age > maxAge) return false; const distance = distanceKm(Number(me.latitude), Number(me.longitude), Number(profile.latitude), Number(profile.longitude)); return Boolean(profile.flight_mode) || distance <= maxDistance; }).map(profile => ({ ...profileShape(profile), distance_km: profile.flight_mode ? null : Math.round(distanceKm(Number(me.latitude), Number(me.longitude), Number(profile.latitude), Number(profile.longitude)) * 10) / 10, worldwide: Boolean(profile.flight_mode) })); json(res, 200, { result }) }
async function swipes(req, res) { const user = await userFor(req); const supabase = client(req); const input = await body(req); const { data: target } = await supabase.from('liebena_profiles').select('id').or(`id.eq.${input.target_id || ''},email.eq.${input.target_email || input.match || ''}`).maybeSingle(); if (!target || target.id === user.id) return json(res, 404, { message: 'User not found.' }); const direction = input.direction === 'like' ? 'like' : 'pass'; const { error } = await supabase.from('liebena_swipes').upsert({ swiper_id: user.id, target_id: target.id, direction }, { onConflict: 'swiper_id,target_id' }); if (error) return json(res, 400, { message: error.message }); let matched = false; if (direction === 'like') { const { data: reciprocal } = await supabase.from('liebena_swipes').select('id').eq('swiper_id', target.id).eq('target_id', user.id).eq('direction', 'like').maybeSingle(); if (reciprocal) { matched = true; await supabase.from('liebena_matches').upsert({ user_id: user.id, matched_user_id: target.id }, { onConflict: 'user_id,matched_user_id' }); } } return json(res, 201, { matched, message: matched ? 'It is a match.' : direction === 'like' ? 'Like sent.' : 'Passed.' }) }
async function likes(req, res) { const user = await userFor(req); const supabase = client(req); if (req.method === 'POST') return swipes(req, res); const { data: received, error } = await supabase.from('liebena_swipes').select('swiper_id').eq('target_id', user.id).eq('direction', 'like'); if (error) return json(res, 400, { message: error.message }); const ids = (received || []).map(row => row.swiper_id); if (!ids.length) return json(res, 200, { result: [], count: 0 }); const { data: profiles, error: profileError } = await supabase.from('liebena_profiles').select('*').in('id', ids); if (profileError) return json(res, 400, { message: profileError.message }); return json(res, 200, { result: (profiles || []).map(profileShape), count: profiles?.length || 0 }) }
async function matches(req, res) { const user = await userFor(req); const supabase = client(req); const { data: outgoing } = await supabase.from('liebena_swipes').select('target_id').eq('swiper_id', user.id).eq('direction', 'like'); const { data: incoming } = await supabase.from('liebena_swipes').select('swiper_id').eq('target_id', user.id).eq('direction', 'like'); const incomingIds = new Set((incoming || []).map(row => row.swiper_id)); const ids = (outgoing || []).map(row => row.target_id).filter(id => incomingIds.has(id)); if (!ids.length) return json(res, 200, { result: [] }); const { data: profiles, error } = await supabase.from('liebena_profiles').select('*').in('id', ids); if (error) return json(res, 400, { message: error.message }); json(res, 200, { result: (profiles || []).map(profileShape) }) }
async function messages(req, res) { const user = await userFor(req); const supabase = client(req); if (req.method === 'POST') { const input = await body(req); const receiverId = String(input.receiver_id || '');
    const { data: receiver } = await supabase.from('liebena_profiles').select('id').or(`id.eq.${receiverId},email.eq.${receiverId}`).maybeSingle();
    if (!receiver || receiver.id === user.id) return json(res, 400, { message: 'A valid conversation recipient is required.' });
    const messageType = input.type === 'media' ? 'image' : (input.type || 'text');
    const { data, error } = await supabase.from('liebena_messages').insert({ sender_id: user.id, receiver_id: receiver.id, content: input.content || null, message_type: messageType, media_pathname: input.media_pathname || null }).select().single(); if (error) return json(res, 400, { message: error.message }); return json(res, 201, { result: data }) } const receiverKey = new URL(req.url, 'https://localhost').searchParams.get('receiver_id') || new URL(req.url, 'https://localhost').searchParams.get('receiver'); let query = supabase.from('liebena_messages').select('*').or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`).order('created_at'); if (receiverKey) { const { data: receiver } = await supabase.from('liebena_profiles').select('id').or(`id.eq.${receiverKey},email.eq.${receiverKey}`).maybeSingle(); if (!receiver) return json(res, 200, { result: [] }); query = supabase.from('liebena_messages').select('*').or(`and(sender_id.eq.${user.id},receiver_id.eq.${receiver.id}),and(sender_id.eq.${receiver.id},receiver_id.eq.${user.id})`).order('created_at'); } const { data, error } = await query; if (error) return json(res, 400, { message: error.message }); json(res, 200, { result: data || [] }) }
async function upload(req, res) { const user = await userFor(req); if (req.method !== 'POST') return json(res, 405, { message: 'Method not allowed.' }); const input = await body(req); const contentType = String(input.content_type || ''); const size = Number(input.size_bytes || 0); if (!/^image\/(jpeg|png|webp|gif)$/.test(contentType) || size <= 0 || size > 8 * 1024 * 1024) return json(res, 400, { message: 'Invalid image.' }); const pathname = `liebena/${user.id}/${crypto.randomUUID()}`; const blob = await put(pathname, Buffer.from(input.base64, 'base64'), { access: 'public', contentType }); const { error } = await client(req).from('liebena_profile_photos').insert({ user_id: user.id, pathname: blob.pathname, url: blob.url, content_type: contentType, size_bytes: size }); if (error) { await del(blob.url); return json(res, 400, { message: error.message }) } await client(req).from('liebena_profiles').update({ profile_picture: blob.url }).eq('id', user.id); json(res, 200, { url: blob.url, pathname: blob.pathname, message: 'Profile image updated.' }) }

module.exports = async function handler(req, res) { try { const p = path(req); if (p === 'auth/register') return register(req,res); if (p === 'auth/login') return login(req,res); if (p === 'auth/logout') return json(res,200,{message:'Logged out.'}); if (p === 'user/profile') return profile(req,res); if (p === 'user/location') { const user = await userFor(req); const input = await body(req); const latitude = Number(input.latitude); const longitude = Number(input.longitude); if (!Number.isFinite(latitude) || !Number.isFinite(longitude) || latitude < -90 || latitude > 90 || longitude < -180 || longitude > 180) return json(res, 400, { message: 'Invalid location.' }); const { error } = await client(req).from('liebena_profiles').update({ latitude, longitude, location_updated_at: new Date().toISOString() }).eq('id', user.id); if (error) return json(res, 400, { message: error.message }); return json(res, 200, { message: 'Location updated.' }); } if (p === 'user/all') return users(req,res); if (p === 'matches') return matches(req,res); if (p === 'likes' || p === 'swipes') return likes(req,res); if (p === 'messages' || p === 'message' || p === 'message/users') return messages(req,res); if (p === 'user/profile-image') return upload(req,res); return json(res,404,{message:'API route not found.'}) } catch (error) { if (error.message === 'UNAUTHORIZED') return json(res,401,{message:'Authentication required.'}); if (error.message === 'INVALID_JSON') return json(res,400,{message:'Invalid request.'}); console.error('[v0] API error', error); return json(res,500,{message:'Unexpected server error.'}) } }
